name: pubs
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Git
#  connection_native_halo:
#    git:
#      url: https://git.hahalolo.com/scm/msoc/flutter-plugin.git
#      ref: e2cb175dba5

  # File
  auto_size_text:
    path: auto_size_text
  cached_network_image:
    path: cached_network_image
  card_swiper:
    path: card_swiper
  carousel_slider:
    path: carousel_slider
  dotted_border:
    path: dotted_border
  dotted_line:
    path: dotted_line
  effective_dart:
    path: effective_dart
  expandable:
    path: expandable
  expansion_tile_card:
    path: expansion_tile_card
  group_list_view:
    path: group_list_view
  infinite_scroll_pagination:
    path: infinite_scroll_pagination
  jiffy:
    path: jiffy
  keyboard_actions:
    path: keyboard_actions
  loading_overlay_pro:
    path: loading_overlay_pro
  modal_bottom_sheet:
    path: modal_bottom_sheet
  notification_center:
    path: notification_center
  photo_view:
    path: photo_view
  pie_chart:
    path: pie_chart
  pin_code_fields:
    path: pin_code_fields
  showcaseview:
    path: showcaseview
  timeago:
    path: timeago
  # Server
  easy_localization: ^3.0.0
  hive: ^2.0.4
  libphonenumber: ^2.0.2
  equatable: ^2.0.3
  flutter_spinkit:
  google_fonts:
  mask_text_input_formatter: ^2.1.0
  flutter_rating_bar:
  cupertino_icons: ^1.0.2
  freezed: '>=2.0.0'
  json_serializable: ^6.0.5
  json_annotation: ^4.4.0
  intl: ^0.17.0
  build_runner: ^2.1.7
  meta: ^1.7.0
  flutter_lints: ^1.0.0
  encrypt: ^5.0.1
  flutter_bloc: ^7.0.1
  dartz: ^0.10.1
  rxdart: ^0.27.3
  lottie: ^1.3.0
  synchronized: ^3.0.0+2
  injectable:
  get_it:
  package_info_plus: ^1.3.0
  connectivity_plus: ^2.2.0
  network_info_plus: ^2.1.2
  http: ^0.13.4
  dio: ^4.0.6
  retrofit: '>=3.0.0 <4.0.0'
  pigeon: ">=2.0.3 <3.2.7"
  args: ^2.3.1
  provider: ^6.0.2
  device_info: ^2.0.3
  html: ^0.15.0
  duration: ^3.0.8
  url_launcher: ^6.0.4-nullsafety
  logging: ^1.0.1
  pointycastle: ^3.5.1
  pedantic: ^1.10.0
  convert: ^3.0.0
  freezed_annotation: ^2.2.0
  tus_client: ^1.0.2
  image_picker: ^0.8.6
  flutter_html: ^3.0.0-alpha.3
  bloc_concurrency: ^0.1.0
  shared_preferences: ^2.0.15
  path_provider: 2.0.11
  webview_flutter: ^2.0.4
  vector_math:
  uuid:
  google_maps_flutter: ^2.1.2
  async: ^2.8.2
  syncfusion_flutter_charts: ^20.2.46
  yaml: ^3.0.0
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: '<=5.4.3+7'
  mockito: ^5.1.0
  path_drawing: ^1.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  chopper_generator:
  flutter_secure_storage: ^5.0.2
  flutter_plugin_android_lifecycle: ^2.0.6
  intl_phone_number_input:
  share_plus: ^4.0.4
  bloc_test: #^8.0.2
  injectable_generator: